# Generated by Django 3.2.5 on 2021-07-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='username',
            field=models.CharField(default='user', max_length=128, verbose_name='Username'),
        ),
    ]
