# Generated by Django 3.2.5 on 2021-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tab_url',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Tab url'),
        ),
    ]
